name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build da imagem Docker
      run: docker build -t ghcr.io/ricardomms10/devops-bible-verse-app/bible-app:latest .

    - name: Push da imagem
      run: docker push ghcr.io/ricardomms10/devops-bible-verse-app/bible-app:latest