name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build da imagem Docker
      run: docker build -t ghcr.io/ricardomms10/devops-bible-verse-app/bible-app:latest .

    - name: Push da imagem
      run: docker push ghcr.io/ricardomms10/devops-bible-verse-app/bible-app:latest


  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Deploy na EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
         docker pull ghcr.io/ricardomms10/devops-bible-verse-app/bible-app:latest
         docker stop $(docker ps -q) || true
         docker rm $(docker ps -aq) || true
         docker run -d -p 3000:3000 --name bible-app ghcr.io/ricardomms10/devops-bible-verse-app/bible-app:latest